{
 "title": "huawei_lte_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "4G", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "sinr",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sinr" }
   ]
  },
  {
   "title": "rsrq",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "targets": [
    { "expr": "rsrq" }
   ]
  },
  {
   "title": "rssi",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "expr": "rssi" }
   ]
  },
  {
   "title": "rsrp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "rsrp" }
   ]
  },
  {
   "title": "4G RSRQ & SINR by Band",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    { "expr": "rsrq{}", "legendFormat": "rsrq {{band}}" },
    { "expr": "sinr{}", "legendFormat": "sinr {{band}}" }
   ]
  },
  {
   "title": "4G RSRP &  RSSI by Band",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    { "expr": "rsrp{}", "legendFormat": "rsrp {{band}}" },
    { "expr": "rssi{}", "legendFormat": "rssi {{band}}" }
   ]
  },
  {
   "title": "4G Band",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "band{}" }
   ]
  },
  { "title": "3G", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "rssi",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rssi" }
   ]
  },
  {
   "title": "rscp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "targets": [
    { "expr": "rscp" }
   ]
  },
  {
   "title": "ec/io",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "targets": [
    { "expr": "ecio" }
   ]
  }
 ]
}